version: "3.3"

services:
  serverudp:
    image: python:alpine
    ports:
      - 12345:12345/udp
    volumes:
      - ./:/server
    command: python3 /server/server-udp.py
  web:
    ports:
      - 8000:8000
    build:
      context: ./
      dockerfile: web.Dockerfile
    volumes:
      - ../udp:/app/src
