version: "3.3"

services:
  servertcp:
    build:
      context: ./
      dockerfile: luasocket.Dockerfile
    ports:
      - 12345:12345/tcp
    volumes:
      - ./:/server
    command: lua /server/server-tcp.lua