version: "3.3"

services:
  serverudp:
    build:
      context: ./
      dockerfile: luasocket.Dockerfile
    ports:
      - 12345:12345/udp
    volumes:
      - ./:/server
    command: lua /server/server-udp.lua