version: "3.3"

services:
  serverudp:
    build:
      context: ./
      dockerfile: Dockerfile-luasocket
    ports:
      - 12345:12345
    volumes:
      - ./:/server
    command: lua /server/server-udp.lua