# This is node build of love app + static webserver

FROM node:15.14.0-alpine3.10 as web

COPY udp /app/src

RUN npm i -g love.js nano-server && love.js /app/src /app/pub --title "UDP Demo" --memory 67108864

WORKDIR /app/pub

CMD nano-server 8000