version: "3.3"

services:
  servertcp:
    build:
      context: ./
      dockerfile: Dockerfile-luasocket
    ports:
      - 12345:12345/tcp
    volumes:
      - ./:/server
    command: lua /server/server-tcp.lua
  web:
    ports:
      - 8000:8000
    build:
      context: ../
      dockerfile: servers/Dockerfile-webtcp