version: "3.3"

services:
  servertcp:
    image: python:alpine
    ports:
      - 12345:12345/tcp
    volumes:
      - ./:/server
    command: python3 /server/server-tcp.py
  web:
    ports:
      - 8000:8000
    build:
      context: ./
      dockerfile: web.Dockerfile
    volumes:
      - ../tcp:/app/src
